### ISSUE TITLE
Repo doesn't meet Catppuccin standards

### ISSUE THREAD

**Issue by elkrien** [catppuccin/lxqt#1]
Please update repo to style guide: https://github.com/catppuccin/style-guide and template: https://github.com/catppuccin/template

**Comment by DonutDev** [comment]
I'm sorry, but I'm not sure what is wrong with the README? Unless it's something obvious I overlooked

**Comment by elkrien** [comment]
I made a PR in Your different repo - You can look there what I have corrected. Two first lines in Readme are not necessary. Now it looks like two titles. Also links for stars, issues and contributors are from template repo instead of this one. 
Also there are no directories like assets or src in repo. 
I know that this are details but we should be consistent with other repos.

**Comment by DonutDev** [comment]
Fixed everything besides the directories.
The images are basically hard coded into the QML file. So I cannot just move them, but I will try making the code use the assets folder

**Comment by DonutDev** [comment]
Also merged your pull request for the sddm theme, thanks!
